<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="sk" lang="sk">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="robots" content="{$robots}" n:ifset="$robots" />
	<title>{block #title}NetCMS{/block}</title>
	
	<link rel="stylesheet" href="{$basePath}/css/login.css" type="text/css" media="screen, projection, tv" />
</head>
<body>

<div id="content">
	<h1>{block #h1}Administrace{/block}</h1> 
	
	<div id="login">
		{foreach $flashes as $flash}<div class="flash {$flash->type}">{$flash->message}</div>{/foreach}
		
		{include #content}
	</div>
</div>
<!-- /#content --> 

</body>
</html>
