<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs" lang="cs">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="robots" content="{$robots}" n:ifset="$robots" />
	<title>{block #title}NetCMS{/block}</title>
	
	<link rel="shortcut icon" href="{$basePath}/favicon.ico" type="image/x-icon" />
	
	<!-- blueprint -->
	<link rel="stylesheet" href="{$basePath}/css/blueprint/screen.css" type="text/css" media="screen, projection, tv" />
	<link rel="stylesheet" href="{$basePath}/css/blueprint/print.css" type="text/css" media="print" />
	<!--[if lt IE 8]><link rel="stylesheet" href="{$basePath}/css/blueprint/ie.css" type="text/css" media="screen, projection"><![endif]-->
	
	<link rel="stylesheet" href="{$basePath}/css/admin.css" type="text/css" media="screen, projection, tv" />
	<link rel="stylesheet" href="{$basePath}/css/ui-lightness/jquery-ui-1.8.6.custom.css" type="text/css" />
	
	<script type="text/javascript" src="{$basePath}/js/jquery-1.4.2.min.js"></script>
	<script type="text/javascript" src="{$basePath}/js/jquery-ui-1.8.6.custom.min.js"></script>
	<script type="text/javascript" src="{$basePath}/js/ckeditor/ckeditor.js"></script>
	<script type="text/javascript" src="{$basePath}/js/jquery.nette.js"></script>
	<script type="text/javascript" src="{$basePath}/js/jquery.ajaxform.js"></script>
	<script type="text/javascript">
$("form.ajax").live("submit", function () {
    $(this).ajaxSubmit();
    return false;
});

$("form.ajax :submit").live("click", function () {
    $(this).ajaxSubmit();
    return false;
});
	</script>
</head>
<body>

<!-- #wrapper -->
<div id="wrapper" class="container">

  <!-- #header -->
  <div id="header" class="span-24 last">
  	<div class="span-12">
	  <a href="{plink Default:}">Admin</a> &nbsp; | &nbsp;  
	  <a href="{$basePath}/">Stránka</a>
	</div>

    <div id="userbox" class="span-12 last">
      {if isset($user)}
      <p>
        <strong>{$user->name}</strong> |
        <a href="{link Auth:logout}">odhlásit</a>
      </p>
      {/if}
    </div>
  </div>
  <hr />
  <!-- /#header -->
  
  <!-- #sibebar -->
  <div id="sidebar" class="span-4">
    <br />
    <br />
    <br />
    
    <ul>
      <li><a href="{plink Page:}">Stránky</a></li>
  	  <li><a href="{plink News:}">Novinky</a></li>
  	  <li><a href="{plink Calendar:}">Kalendář</a></li>
  	  <li><a href="{plink Photogallery:}">Fotogalerie</a></li>
  	  <li><a href="{plink File:}">Soubory</a></li>
  	  <li><a href="{plink Template:}">Šablony</a></li>
  	  <li><a href="{plink Translation:}">Překlady</a></li>
  	  <li><a href="{plink Seed:}">Osiva</a></li>
  	  <li><a href="{plink Blog:}">Blog</a></li>
  	  <li><a href="{plink Emailing:}">E-maily</a></li>
  	  <li><a href="{plink Contact:}">Problém</a></li>
  	</ul>
  </div>
  <!-- /#sidebar -->
  
  <!-- #content -->
  <div id="content" class="span-20 last">
  	
  	<h1>{block #h1}Administrace{/block}</h1>
  	
  	{snippet flashMessage}
    {foreach $flashes as $flash}
    	<div class="{if $flash->type != null}{$flash->type}{else}notice{/if}">{!$flash->message}</div>
    {/foreach}
    {/snippet}
    
    {include #content}
    
    <!-- #footer -->
    <div id="footer">
      <span class="quiet">Copyright &copy; 2010 - {? echo date('Y')} &nbsp; | &nbsp; NetCMS</span>
    </div>
    <!-- /#footer -->
  </div>
  <!-- /#content -->

</div>
<!-- /#wrapper -->
</body>
</html>
