<script type="text/javascript">
//<![CDATA[
CKEDITOR.replace('pageContent', {
	language: 'cs',
	width: 600,
	toolbar: [
		['Source'],
		['Cut','Copy','Paste','PasteText','PasteFromWord'],
		['Undo','Redo'], '/',
		['Format'],
		['Bold','Italic'],
		['NumberedList','BulletedList'],
		['Link','Unlink'],
		['Image','Table','SpecialChar'],
	],
	filebrowserBrowseUrl : '{!basePath}/admin/chooser/images/',
	extraPlugins:'highslide',
	menu_groups:'highslide,clipboard,form,tablecell,tablecellproperties,tablerow,tablecolumn,table,anchor,link,image,flash,checkbox,radio,textfield,hiddenfield,imagebutton,button,select,textarea,div',
});
//]]>
</script>
