<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="sk" lang="sk">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="robots" content="{$robots}" n:ifset="$robots" />
	<title>{block #title}NetCMS{/block}</title>
	
	<!-- blueprint --/>
	<link rel="stylesheet" href="{$basePath}/css/blueprint/screen.css" type="text/css" media="screen, projection, tv" />
	<link rel="stylesheet" href="{$basePath}/css/blueprint/print.css" type="text/css" media="print" />
	<!--[if lt IE 8]><link rel="stylesheet" href="{$basePath}/css/blueprint/ie.css" type="text/css" media="screen, projection"><![endif]-->
	<!-- /blueprint -->
	
	<link rel="stylesheet" href="{$basePath}/css/admin.css" type="text/css" media="screen, projection, tv" />
</head>
<body>

<!-- #wrapper -->
<div>
	{include #content}
</div>
<!-- /#wrapper -->
</body>
</html>
