
CREATE TABLE `news` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(255) COLLATE utf8_czech_ci NOT NULL DEFAULT '',
	`text` TEXT COLLATE utf8_czech_ci NOT NULL DEFAULT '',
	`created` datetime NOT NULL,
	`visible` tinyint(1) NOT NULL DEFAULT '1',
	PRIMARY KEY (`id`)
) ENGINE = INNODB DEFAULT CHARSET=utf8 COLLATE utf8_czech_ci;


CREATE TABLE `page` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL DEFAULT '',
	`url` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL DEFAULT '',
	`title` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL DEFAULT '',
	`content` TEXT CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL DEFAULT '',
	`visible` TINYINT(1) NOT NULL DEFAULT '1',
	`position` INT UNSIGNED NOT NULL,
	`template` VARCHAR(30) NOT NULL DEFAULT '',
	`parentUrl` VARCHAR(255) NOT NULL DEFAULT '',
	`redirect` VARCHAR(255) NOT NULL DEFAULT '', -- added 6 May 2011
	PRIMARY KEY (`id`),
	UNIQUE (`name`, `url`),
	INDEX (`url`),
	KEY (`url`)
) ENGINE = INNODB DEFAULT CHARSET=utf8 COLLATE utf8_czech_ci;

INSERT INTO `page` (`id`, `name`, `url`, `title`, `content`, `visible`, `position`, `template`) 
VALUES (1, '', '', 'Home page', '<h1>Home page</h1><p>Text text text</p>', 1, 1, 'default');


CREATE TABLE `translation` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	`original` VARCHAR( 255 ) NOT NULL,
	`translation` VARCHAR( 255 ) NOT NULL,
	UNIQUE (`original`, `translation`)
) ENGINE = INNODB CHARACTER SET utf8 COLLATE utf8_czech_ci;


CREATE TABLE `seed` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	`name` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL DEFAULT  '',
	`description` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL DEFAULT  ''
) ENGINE = INNODB CHARACTER SET utf8 COLLATE utf8_czech_ci;

CREATE TABLE `seedItem` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`seedId` INT UNSIGNED NOT NULL,
	`name` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL DEFAULT  '',
	`resistence` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL DEFAULT  '',
	`color` CHAR( 1 ) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL DEFAULT  '',
	`position` INT( 10 ) UNSIGNED NOT NULL,
	`w1` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w2` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w3` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w4` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w5` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w6` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w7` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w8` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w9` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w10` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w11` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w12` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w13` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w14` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w15` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w16` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w17` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w18` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w19` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w20` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w21` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w22` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w23` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w24` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w25` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w26` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w27` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w28` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w29` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w30` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w31` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w32` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w33` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w34` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w35` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w36` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w37` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w38` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w39` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w40` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w41` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w42` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w43` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w44` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w45` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w46` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w47` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w48` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w49` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w50` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w51` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0',
	`w52` TINYINT( 2 ) UNSIGNED NOT NULL DEFAULT  '0'
) ENGINE = MYISAM CHARACTER SET utf8 COLLATE utf8_czech_ci;


CREATE TABLE `emailing` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	`email` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL
) ENGINE = INNODB CHARACTER SET utf8 COLLATE utf8_czech_ci;


CREATE TABLE `blog` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(255) COLLATE utf8_czech_ci NOT NULL DEFAULT '',
	`text` TEXT COLLATE utf8_czech_ci NOT NULL DEFAULT '',
	`created` datetime NOT NULL,
	`visible` tinyint(1) NOT NULL DEFAULT '1',
	PRIMARY KEY (`id`)
) ENGINE = INNODB DEFAULT CHARSET=utf8 COLLATE utf8_czech_ci;


