{block #title}Přidat záznam | {include #parent}{/block}
{block #h1}Přidat záznam{/block}

{block #content}
<script>
$(function() {
	$(".datepicker").datepicker({
		// showOn: "button",
		// buttonImage: "{!$basePath}/images/calendar.gif",
		// buttonImageOnly: true,
		dateFormat: 'd. m. yy',
		
		// localize
		closeText: 'Zavřít',
		prevText: '&#x3c; Dříve',
		nextText: 'Později &#x3e;',
		currentText: 'Nyní',
		monthNames: ['leden','únor','březen','duben','květen','červen','červenec','srpen','září','říjen','listopad','prosinec'],
		monthNamesShort: ['led','úno','bře','dub','kvě','čer','čvc','srp','zář','říj','lis','pro'],
		dayNames: ['neděle', 'pondělí', 'úterý', 'středa', 'čtvrtek', 'pátek', 'sobota'],
		dayNamesShort: ['ne', 'po', 'út', 'st', 'čt', 'pá', 'so'],
		dayNamesMin: ['ne','po','út','st','čt','pá','so'],
		weekHeader: 'Týd',
		firstDay: 1,
		isRTL: false,
		showMonthAfterYear: false,
		yearSuffix: '',
	});
});
</script>
{widget calendarForm}{/block}

