{block #title}{block #h1}Kalendář{/block} | {include #parent}{/block}
{block #content}

<p><a href="{link add}">Přidat záznam</a></p>

<table class="grid">
<tr>
	<th>Datum</th>
	<th>Text</th>
	<th>Akce</th>
</tr>

{foreach $itemsCollection as $item}
<tr>
	<td>{$item->getDate()|date:'%e. %-m. %Y'}</td>
	<td>{$item->getText()|truncate:80}</td>
	<td>
		<a href="{link edit, $item->getId()}">Upravit</a> &nbsp;
		<a href="{link delete, $item->getId()}">Smazat</a>
	</td>
</tr>
{/foreach}
</table>
{/block}
