{block #title}Novinky | {include #parent}{/block}
{block #h1}Novinky{/block}

{block #content}

<p><a href="{link add}">Přidat novinku</a></p>

<table class="grid">
<tr>
	<th>Nadpis</th>
	<th>Datum</th>
	<th>Akce</th>
</tr>

{foreach $items as $item}
<tr>
	<td>{$item->getTitle()}</td>
	<td>{$item->getCreated()}</td>
	<td>
		<a href="{link pdf, $item->getId()}">PDF</a> &nbsp;
		<a href="{link edit, $item->getId()}">Upravit</a> &nbsp;
		<a href="{link delete, $item->getId()}">Smazat</a>
	</td>
</tr>
{/foreach}
</table>

{/block}
