{block #title}Novinky | {include #parent}{/block}
{block #h1}Novinky{/block}

{block #content}

<p><a href="{link add}">Přidat novinku</a></p>

<table class="grid">
<tr>
	<th>Nadpis</th>
	<th>Text</th>
	<th>Akce</th>
</tr>

{foreach $newsCollection as $news}
<tr>
	<td>{$news->getTitle()}</td>
	<td>{$news->getText()}</td>
	<td>
		<a href="{link edit, $news->getId()}">Upravit</a> &nbsp;
		<a href="{link delete, $news->getId()}">Smazat</a>
	</td>
</tr>
{/foreach}
</table>
