<script type="text/javascript">
//<![CDATA[
CKEDITOR.replace('pageContent', {
	language: 'cs',
	width: 600,
	toolbar: [
		['Source'],
		['Cut','Copy','Paste','PasteText','PasteFromWord'],
		['Undo','Redo'], '/',
		['Format'],
		['Bold','Italic'],
		['NumberedList','BulletedList'],
		['Link','Unlink'],
		['Image','Table','SpecialChar'],
	],
	filebrowserBrowseUrl : '{!basePath}/admin/chooser/images/',
});
//]]>
</script>
