<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<title>{$page->getTitle()} | NetCMS</title>
	
	<link rel="stylesheet" type="text/css" media="screen" href="{$basePath}/css/frontend.css" />
</head>

<body>
  <div id="header">
    Header {? echo date('Y')}
    {if !empty($translation)}Translation: <a href="{link :Front:Default: $translation}">{$translationLanguage}</a>{/if}
  </div>

  <div id="sidebar">
    {widget menu, $url}
    {widget news}
  </div>

  <div id="content">
    {widget breadcrumbs, $url}
    {block content}
    <!-- {$moduleName} {$presenterName} {$viewName} {$template->getFile()} {$presenter->template->getFile()} {link :Admin:Default:} -->
  </div>
</body>
</html>