<div id="seed">
{if !empty($seed)}
<table>
<tr>
  <th colspan="2">Rijk Zwaan</th>
  <th colspan="52">{$seed->getName()}</th>
</tr>
<tr>
  <th colspan="2">&nbsp;</th>
  <th colspan="5">Leden</th>
  <th colspan="4">Únor</th>
  <th colspan="4">Březen</th>
  <th colspan="5">Duben</th>
  <th colspan="4">Květen</th>
  <th colspan="4">Červen</th>
  <th colspan="5">Červenec</th>
  <th colspan="4">Srpen</th>
  <th colspan="4">Září</th>
  <th colspan="4">Říjen</th>
  <th colspan="5">Listopad</th>
  <th colspan="4">Prosinec</th>
</tr>
<tr>
  <th>Odrůda</th>
  <th>Rezistence</th>
  <th>1</th>
  <th>2</th>
  <th>3</th>
  <th>4</th>
  <th>5</th>
  <th>6</th>
  <th>7</th>
  <th>8</th>
  <th>9</th>
  <th>10</th>
  <th>11</th>
  <th>12</th>
  <th>13</th>
  <th>14</th>
  <th>15</th>
  <th>16</th>
  <th>17</th>
  <th>18</th>
  <th>19</th>
  <th>20</th>
  <th>21</th>
  <th>22</th>
  <th>23</th>
  <th>24</th>
  <th>25</th>
  <th>26</th>
  <th>27</th>
  <th>28</th>
  <th>29</th>
  <th>30</th>
  <th>31</th>
  <th>32</th>
  <th>33</th>
  <th>34</th>
  <th>35</th>
  <th>36</th>
  <th>37</th>
  <th>38</th>
  <th>39</th>
  <th>40</th>
  <th>41</th>
  <th>42</th>
  <th>43</th>
  <th>44</th>
  <th>45</th>
  <th>46</th>
  <th>47</th>
  <th>48</th>
  <th>49</th>
  <th>50</th>
  <th>51</th>
  <th>52</th>
</tr>
{foreach $seedItems as $item}
<tr>
  <td>{!$item->getName()}</td>
  <td>{$item->getResistence()}</td>
  <td>{if $item->getW1() & 1}-{/if}</td>
  <td>{if $item->getW2() & 1}-{/if}</td>
  <td>{if $item->getW3() & 1}-{/if}</td>
  <td>{if $item->getW4() & 1}-{/if}</td>
  <td>{if $item->getW5() & 1}-{/if}</td>
  <td>{if $item->getW6() & 1}-{/if}</td>
  <td>{if $item->getW7() & 1}-{/if}</td>
  <td>{if $item->getW8() & 1}-{/if}</td>
  <td>{if $item->getW9() & 1}-{/if}</td>
  <td>{if $item->getW10() & 1}-{/if}</td>
  <td>{if $item->getW11() & 1}-{/if}</td>
  <td>{if $item->getW12() & 1}-{/if}</td>
  <td>{if $item->getW13() & 1}-{/if}</td>
  <td>{if $item->getW14() & 1}-{/if}</td>
  <td>{if $item->getW15() & 1}-{/if}</td>
  <td>{if $item->getW16() & 1}-{/if}</td>
  <td>{if $item->getW17() & 1}-{/if}</td>
  <td>{if $item->getW18() & 1}-{/if}</td>
  <td>{if $item->getW19() & 1}-{/if}</td>
  <td>{if $item->getW20() & 1}-{/if}</td>
  <td>{if $item->getW21() & 1}-{/if}</td>
  <td>{if $item->getW22() & 1}-{/if}</td>
  <td>{if $item->getW23() & 1}-{/if}</td>
  <td>{if $item->getW24() & 1}-{/if}</td>
  <td>{if $item->getW25() & 1}-{/if}</td>
  <td>{if $item->getW26() & 1}-{/if}</td>
  <td>{if $item->getW27() & 1}-{/if}</td>
  <td>{if $item->getW28() & 1}-{/if}</td>
  <td>{if $item->getW29() & 1}-{/if}</td>
  <td>{if $item->getW30() & 1}-{/if}</td>
  <td>{if $item->getW31() & 1}-{/if}</td>
  <td>{if $item->getW32() & 1}-{/if}</td>
  <td>{if $item->getW33() & 1}-{/if}</td>
  <td>{if $item->getW34() & 1}-{/if}</td>
  <td>{if $item->getW35() & 1}-{/if}</td>
  <td>{if $item->getW36() & 1}-{/if}</td>
  <td>{if $item->getW37() & 1}-{/if}</td>
  <td>{if $item->getW38() & 1}-{/if}</td>
  <td>{if $item->getW39() & 1}-{/if}</td>
  <td>{if $item->getW40() & 1}-{/if}</td>
  <td>{if $item->getW41() & 1}-{/if}</td>
  <td>{if $item->getW42() & 1}-{/if}</td>
  <td>{if $item->getW43() & 1}-{/if}</td>
  <td>{if $item->getW44() & 1}-{/if}</td>
  <td>{if $item->getW45() & 1}-{/if}</td>
  <td>{if $item->getW46() & 1}-{/if}</td>
  <td>{if $item->getW47() & 1}-{/if}</td>
  <td>{if $item->getW48() & 1}-{/if}</td>
  <td>{if $item->getW49() & 1}-{/if}</td>
  <td>{if $item->getW50() & 1}-{/if}</td>
  <td>{if $item->getW51() & 1}-{/if}</td>
  <td>{if $item->getW52() & 1}-{/if}</td>
  {*{? var_export($item)}*}
</tr>
<tr>
  <td>&nbsp;</td>
  <td>&nbsp;</td>
  <td>{if $item->getW1() & 2}-{/if}</td>
  <td>{if $item->getW2() & 2}-{/if}</td>
  <td>{if $item->getW3() & 2}-{/if}</td>
  <td>{if $item->getW4() & 2}-{/if}</td>
  <td>{if $item->getW5() & 2}-{/if}</td>
  <td>{if $item->getW6() & 2}-{/if}</td>
  <td>{if $item->getW7() & 2}-{/if}</td>
  <td>{if $item->getW8() & 2}-{/if}</td>
  <td>{if $item->getW9() & 2}-{/if}</td>
  <td>{if $item->getW10() & 2}-{/if}</td>
  <td>{if $item->getW11() & 2}-{/if}</td>
  <td>{if $item->getW12() & 2}-{/if}</td>
  <td>{if $item->getW13() & 2}-{/if}</td>
  <td>{if $item->getW14() & 2}-{/if}</td>
  <td>{if $item->getW15() & 2}-{/if}</td>
  <td>{if $item->getW16() & 2}-{/if}</td>
  <td>{if $item->getW17() & 2}-{/if}</td>
  <td>{if $item->getW18() & 2}-{/if}</td>
  <td>{if $item->getW19() & 2}-{/if}</td>
  <td>{if $item->getW20() & 2}-{/if}</td>
  <td>{if $item->getW21() & 2}-{/if}</td>
  <td>{if $item->getW22() & 2}-{/if}</td>
  <td>{if $item->getW23() & 2}-{/if}</td>
  <td>{if $item->getW24() & 2}-{/if}</td>
  <td>{if $item->getW25() & 2}-{/if}</td>
  <td>{if $item->getW26() & 2}-{/if}</td>
  <td>{if $item->getW27() & 2}-{/if}</td>
  <td>{if $item->getW28() & 2}-{/if}</td>
  <td>{if $item->getW29() & 2}-{/if}</td>
  <td>{if $item->getW30() & 2}-{/if}</td>
  <td>{if $item->getW31() & 2}-{/if}</td>
  <td>{if $item->getW32() & 2}-{/if}</td>
  <td>{if $item->getW33() & 2}-{/if}</td>
  <td>{if $item->getW34() & 2}-{/if}</td>
  <td>{if $item->getW35() & 2}-{/if}</td>
  <td>{if $item->getW36() & 2}-{/if}</td>
  <td>{if $item->getW37() & 2}-{/if}</td>
  <td>{if $item->getW38() & 2}-{/if}</td>
  <td>{if $item->getW39() & 2}-{/if}</td>
  <td>{if $item->getW40() & 2}-{/if}</td>
  <td>{if $item->getW41() & 2}-{/if}</td>
  <td>{if $item->getW42() & 2}-{/if}</td>
  <td>{if $item->getW43() & 2}-{/if}</td>
  <td>{if $item->getW44() & 2}-{/if}</td>
  <td>{if $item->getW45() & 2}-{/if}</td>
  <td>{if $item->getW46() & 2}-{/if}</td>
  <td>{if $item->getW47() & 2}-{/if}</td>
  <td>{if $item->getW48() & 2}-{/if}</td>
  <td>{if $item->getW49() & 2}-{/if}</td>
  <td>{if $item->getW50() & 2}-{/if}</td>
  <td>{if $item->getW51() & 2}-{/if}</td>
  <td>{if $item->getW52() & 2}-{/if}</td>
</tr>
{/foreach}
</table>
{/if}
</div>